require: rubocop-rspec
inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - lib/**/*.rake
  Exclude:
    - 'vendor/**/*'
    - '*.gemspec'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/RescueException:
  Exclude:
    - 'lib/tasks/*.rake'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 80

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FileName:
  Exclude: ['Gemfile', 'Guardfile']

Style/FormatStringToken:
  EnforcedStyle: template

# Disable Style/NumericLiterals so numbers don't need underscores
Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/RedundantBegin:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
  Exclude:
    - 'Guardfile'

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/VerifiedDoubles:
  Enabled: false
